command: ["npm", "start"]
env:
  - name: 'DATABRICKS_SERVER_HOSTNAME'
    value: 'e2-demo-field-eng.cloud.databricks.com'
  - name: WAREHOUSE_ID
    valueFrom: "warehouse"
  - name: 'DATABRICKS_HTTP_PATH'
    value: '/sql/1.0/warehouses/4b9b953939869799'