command: ["npm", "start"]
env:
  - name: 'DATABRICKS_SERVER_HOSTNAME'
    value: 'xxxx'
  - name: WAREHOUSE_ID
    valueFrom: "warehouse"
  - name: 'DATABRICKS_HTTP_PATH'
    value: '/sql/1.0/warehouses/xxxx'